### ISSUE TITLE
The ES index mapping property _id/path is not working with the plugin

### ISSUE THREAD

**Issue by ebunders** [mattweber/elasticsearch-mocksolrplugin#5]
In ES you can define the source property that the (to be created) document id will be dreived from: 
http://www.elasticsearch.org/guide/reference/mapping/id-field.html

When using this plugin that feature no longer works. 

My solr input document has a property 'id', which I also want to be the id of the ES document.

My ES index mapping looks like this:
{
    "page": {
        "_id": {
            "path": "id",
            "store": "yes"
        },
...

So the id from the input document should be used as id. 

What I guess is that ES only does this when the document is inserted without a specific id, and the plugin creates an id for the document.

I could fix this, but I'm not sure what would be the best approach. Could anybody comment on this?

cheers!

**Comment by mattweber** [comment]
The plugin scans the incoming document for an "id" field which when found it will perform a checksum on that field and use that for the ES id.  This is all transparent to the user assuming you are just trying to mock Solr.  Now, if you are trying to do ES specific things like this, then it could be an issue.  You really dont even need this mapping, just modify the plugin to skip the checksum and the document will be inserted with the correct id.

**Comment by mattweber** [comment]
https://github.com/mattweber/elasticsearch-mocksolrplugin/blob/master/src/main/java/co/diji/rest/SolrUpdateHandlerRestAction.java#L354

Don't call the getMD5 method.

**Comment by ebunders** [comment]
It would be nice to make this choice configurable. But presently there's no runtime configuration that I'm aware of. I'm not really keen on having to maintain my own fork of the code for such a little thing. Perhaps I'll create a patch..
But anyway: thanks for the hint!
